FROM ubuntu:latest

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get -qq -y install curl wget docker
RUN curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/arm64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

WORKDIR /tmp
# install yq
RUN wget https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_arm64 -O yq
RUN chmod +x yq && mv yq /usr/bin/yq

# install helm
RUN curl -LO https://get.helm.sh/helm-v3.7.2-linux-arm64.tar.gz
RUN tar -zxvf helm-v3.7.2-linux-arm64.tar.gz
RUN mv linux-arm64/helm /usr/local/bin/helm