version: 2.1

jobs:
  build:
    # Use `docker:stable` as the Docker container to run this job in
    docker:
      - image: arm64v8/ubuntu
    resource_class: small

    steps:
      # Checkout the repository files
      - checkout

      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker

      # Build the hello world image
      - run:
          name: Build Docker image
          command: docker build --tag simpleapp .
      
      - run: 
          name: Inspect image architecture
          command: docker image inspect simpleapp | grep -i arch

workflows:
  version: 2
  build-push:
    jobs:
      - build
