version: 2.1

jobs:
  build:
    # Use `docker:stable` as the Docker container to run this job in
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    steps:
      # Checkout the repository files
      - checkout

      - run:
          name: "Install Kubectl and Helm"
          command: sh ./kube.sh

      - restore_cache:
          keys:
            - v1-{{ .Branch }}

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: check images
          command: docker image ls

      # Build the hello world image
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -f Dockerfile --tag app .
            helm version
            kubectl version --client
            yq -h

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

workflows:
  version: 2
  build-push:
    jobs:
      - build
