version: 2.1

jobs:
  build:
    # Use `docker:stable` as the Docker container to run this job in
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    steps:
      # Checkout the repository files
      - checkout

      - restore_cache:
          keys:
            - v1-kubetools-{{ checksum ".circleci/kube-tools.sh" }}

      - run:
          name: "Install Kubectl and Helm"
          command: sh .circleci/kube-tools.sh

      - save_cache:
          key: v1-kubetools-{{ checksum ".circleci/kube-tools.sh" }}
          paths:
            - /tmp/tools/kubectl
            - /tmp/tools/helm
            - /tmp/tools/yq

      - restore_cache:
          keys:
            - v1-{{ .Branch }}

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/app.tar | true

      - run:
          name: check images
          command: docker image ls

      # Build the hello world image
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -f Dockerfile --tag app .
            helm version
            kubectl version --client
            yq -h

      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o /tmp/app.tar app

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/app.tar

workflows:
  version: 2
  build-push:
    jobs:
      - build
